### ISSUE TITLE
PyPi Support?

### ISSUE THREAD

**Issue by dwcaraway** [deontologician/restnavigator#2]
Howdy, any chance of getting the rest navigator published on pypi? I found a nice tutorial at http://peterdowns.com/posts/first-time-with-pypi.html.

**Comment by deontologician** [comment]
Hi, I just noticed this, I think I missed the email. I'll get it up on pypi this weekend.

With the caveat that I think the missing embedded support is pretty critical! But I understand the desire to be able to play with it easier than pulling it down from github

**Comment by dwcaraway** [comment]
awesome josh, ty!

On Nov 5, 2013, at 8:43 PM, Josh Kuhn notifications@github.com wrote:

Hi, I just noticed this, I think I missed the email. I'll get it up on pypi
this weekend.

—
Reply to this email directly or view it on
GitHubhttps://github.com/deontologician/rest_navigator/issues/2#issuecomment-27832854
.

**Comment by deontologician** [comment]
Ok! Finally got to this. restnavigator (dropped the underscore on the package name to conform to prevailing standards) is now available on the cheeseshop: https://pypi.python.org/pypi/restnavigator/0.2.0

**Comment by dwcaraway** [comment]
awesome!!!

On Jan 19, 2014, at 6:48 PM, Josh Kuhn notifications@github.com wrote:

Ok! Finally got to this. restnavigator (dropped the hyphen on the package
name to conform to prevailing standards) is now available on the
cheeseshop: https://pypi.python.org/pypi/restnavigator/0.2.0

—
Reply to this email directly or view it on
GitHubhttps://github.com/deontologician/rest_navigator/issues/2#issuecomment-32726484
.
