### ISSUE TITLE
Fail to parse ht:users on haltalk data

### ISSUE THREAD

**Issue by SongChen** [deontologician/restnavigator#3]
There is one name that will be rendered as list but list is not allowed to be the dict key. It will raise: Python error: unhashable type: 'list'

{
        "href": "/users/%5B%22jeffmichaud%22%5D",
        "title": [
          "Jeff Michaud"
        ]
 }

**Comment by deontologician** [comment]
Ha! Nice. Haltalk doesn't escape the names you enter, so it rendered as an actual JSON list:

The offending link:

```
{
    "href": "/users/%5B%22jeffmichaud%22%5D",
    "title": [
        "Jeff Michaud"
    ]
},
```

Looking into the fix now, there's nothing in the HAL specification that says it _can't_ be a list (though I suspect Mike didn't intend for users to be able to do that on his server), so it's good to fix it.

**Comment by deontologician** [comment]
Nevermind, it is prohibited:

```
5.7.  title

   The "title" property is OPTIONAL.

   Its value is a string and is intended for labelling the link with a
   human-readable identifier (as defined by [RFC5988]).
```

But, I think Navigator shouldn't just bail if it's malformed, it should probably do something more reasonable.
