### ISSUE TITLE
Create real api docs with Sphinx

### ISSUE THREAD

**Issue by deontologician** [deontologician/restnavigator#34]
Right now, the readme is bending under its own weight, and there are many undocumented pieces of the api.

**Comment by bubenkoff** [comment]
I can work on that to integrate it with readthedocs, if you'll create a
project for rest navigator there and add me as a collaborator (bubenkoff)

On 9 March 2015 at 06:35, Josh Kuhn notifications@github.com wrote:

> Right now, the readme is bending under its own weight, and there are many
> undocumented pieces of the api.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/deontologician/rest_navigator/issues/34.

## 

Anatoly Bubenkov

**Comment by deontologician** [comment]
Done.

**Comment by bubenkoff** [comment]
Is this http://rest-navigator.readthedocs.org/en/latest/#module-restnavigator enough or you wanted something more?

**Comment by deontologician** [comment]
That looks pretty good to me. I might comb through it later, but since it's automatically building from docstrings it can be fixed up if I notice the docstrings aren't descriptive enough
