### ISSUE TITLE
Autofetch assumes navigator method is always GET

### ISSUE THREAD

**Issue by dudycooly** [deontologician/restnavigator#6]
Considering the usage of  links()

```
@autofetch
def links(self):
    r'''Returns dictionary of navigators from the current resource.'''
    return dict(self._links)
```

def autofetch(fn):
    '''A decorator used by Navigators that fetches the resource if necessary
    prior to calling the function '''

```
@functools.wraps(fn)
def wrapped(self, *args, **qargs):
    if self.response is None:
        self._GET()                      <<<<<<  We may have POST method returning links
    return fn(self, *args, **qargs)
return wrapped
```

**Comment by deontologician** [comment]
OK, so you've got a resource that only returns links after a POST request? In other words, you need the data in the POST to get the right links, and those links aren't a resource in their own right with a GET-able URL?

**Comment by dudycooly** [comment]
Yes. Your understanding is correct.

I am trying some work around by storing method info as an instance property. I will update you once  I have something working.

**Comment by deontologician** [comment]
I am thinking of adding a special navigator that is the result of a post response. it wouldn't be cached like other resources, but would allow you to do things like this. The thing that prevented this before is the lack of a direct get url, so I'll just get rid of that requirement

**Comment by deontologician** [comment]
@dudycooly So for this, I turned autofetch off for all non-idempotent navigators (like PostResponse), and the best way to refetch it from the PostResponse is like:

``` python
>>> pr
PostResponse(...)
>>> pr2 = pr.parent.create({...})
```

That way you can specify the post body that is needed. Overall, autofetch is only safe because GET is an idempotent operation. changing autofetch to run POSTs transparently wouldn't be safe.

Does this solve your use case?

**Comment by dudycooly** [comment]
@deontologician , Yes and No. But I am happy to close this and create specific if needed. 
I have few enhancements. How do you want me to submit for your review?

**Comment by deontologician** [comment]
Oh, I'd say open up a pull request. We can look at the changes there

**Comment by deontologician** [comment]
And yeah, if there is other stuff that remain unfixed, please feel free to open issues for them
