### ISSUE TITLE
Support _embedded

### ISSUE THREAD

**Issue by tuukkamustonen** [deontologician/restnavigator#7]
Apparently `_embedded` fields are not supported, simply snipped away from the response?

**Comment by deontologician** [comment]
Yes! this is a glaring issue that I'm going to solve this week, culminating in a new release.
As a stopgap measure, I pulled the part that was snipping out the embedded key. That was there in anticipation of the real support, but I never got to it

**Comment by bubenkoff** [comment]
Looks like the refactoring didn't help with _embedded support?
im trying to get a collection returned in _embedded, and it doesn't see it

**Comment by deontologician** [comment]
embedded still hasn't been implemented :/

It will be though, I am slowly getting to it

**Comment by bubenkoff** [comment]
Can I help you there?
It's crucial for my use case

**Comment by deontologician** [comment]
I am going to take a shot at it tonight

**Comment by deontologician** [comment]
Well, this was a bad week to quit caffeine. I'm going to keep trying tomorrow on this

**Comment by deontologician** [comment]
OK, I have the first implementation of embedding done. It needs more tests, but it's looking good

**Comment by bubenkoff** [comment]
Great! Ill check it out as soon as possible.
Thanks!

**Comment by bubenkoff** [comment]
I played with embedded a bit:

``` shell
In [22]: Navigator.hal('http://haltalk.herokuapp.com/', apiname="haltalk")['ht:latest-posts']['ht:post'][0].state
Out[22]: 
{u'content': u'having fun w/ the HAL Talk explorer',
 u'created_at': u'2012-07-07T22:35:33+00:00'}
```

``` shell
In [23]: Navigator.hal('http://haltalk.herokuapp.com/', apiname="haltalk")['ht:latest-posts']['ht:post'][0].created_at
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-23-36e605710293> in <module>()
----> 1 Navigator.hal('http://haltalk.herokuapp.com/', apiname="haltalk")['ht:latest-posts']['ht:post'][0].created_at

AttributeError: 'HALNavigator' object has no attribute 'created_at'
```

``` shell
In [24]: Navigator.hal('http://haltalk.herokuapp.com/', apiname="haltalk")['ht:latest-posts']['ht:post'][0].content
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-24-5494536a070b> in <module>()
----> 1 Navigator.hal('http://haltalk.herokuapp.com/', apiname="haltalk")['ht:latest-posts']['ht:post'][0].content

AttributeError: 'HALNavigator' object has no attribute 'content'
```

so it messes up the structure of response as you see

also i noticed a small bug:

``` diff
diff --git a/restnavigator/halnav.py b/restnavigator/halnav.py
index df3d7e1..7b8e2be 100644
--- a/restnavigator/halnav.py
+++ b/restnavigator/halnav.py
@@ -347,7 +347,6 @@ class HALNavigatorBase(object):
                     raise TypeError("{0!r} doesn't accept a traversor of {1!r}"
                                     .format(val, arg))
             except Exception as e:
-                raise
                 raise exc.OffTheRailsException(
                     traversal, i, intermediates, e)
             intermediates.append(val)
```

**Comment by deontologician** [comment]
Ah, that's good to know. The raise was from some debugging, I'll have to remove that.

I've gotten other stuff off my schedule so I should be able to finish it up and get it completely tested this week

**Comment by deontologician** [comment]
@bubenkoff The issue is that the 2nd and third examples need to switch from:

```
...['ht:post'][0].content
...['ht:post'][0].created_at
```

to

```
...['ht:post'][0]()['content']
...['ht:post'][0]()['created_at']
```

Currently, state is just represented as a dict, so it has no special attribute access. You could also do

```
['ht:post'][0].state['created_at']
```

if that's easier to read. If you want to make a proposal to implement an attribute dictionary for state, I wouldn't be opposed, it's definitely nicer syntax.

**Comment by deontologician** [comment]
I don't think all attributes for a document should be proxied to the navigator itself, there is too much potential for a clash

**Comment by deontologician** [comment]
Ok, embedded support is merged into next. @bubenkoff I've added you as a collaborator. If you're so inclined as to contribute again, you can create branches etc directly in the repo. Thanks for the prodding on this!

**Comment by bubenkoff** [comment]
thank you so much for all the efforts you provide for this project!
I'll do my best to help you

**Comment by bubenkoff** [comment]
as to attribute access - now it's clearer for me, thanks
It's a matter of taste, i'll integrate embedded in the project and then will have more feeedback
